-- ============================================================
-- 信息采集模块 - 达梦 DM8 建表 DDL
-- Schema: ZSZJ_INFRAS
-- 在达梦管理工具中以 ZSZJ_INFRAS 用户执行
-- ============================================================

-- 1. 采集任务表
CREATE TABLE IF NOT EXISTS "ZSZJ_INFRAS"."T_COLLECT_TASK" (
    "ID"                VARCHAR(50)     NOT NULL,
    "TASKNAME"          VARCHAR(100)    NOT NULL,
    "TASKDESC"          VARCHAR(500),
    "CREATORTIME"       TIMESTAMP,
    "CREATORUSER"       VARCHAR(50),
    "CREATORUSERNAME"   VARCHAR(50),
    "LASTMODIFYTIME"    TIMESTAMP,
    "LASTMODIFYUSER"    VARCHAR(50),
    "LASTMODIFYUSERNAME" VARCHAR(50),
    "DELETETIME"        TIMESTAMP,
    "DELETEUSER"        VARCHAR(50),
    "DELETEUSERNAME"    VARCHAR(50),
    "ENABLEDMARK"       VARCHAR(10)     DEFAULT '1',
    "SORTCODE"          INT,
    "ORGANIZE"          VARCHAR(50),
    "FLOWPHASE"         VARCHAR(50),
    "STEPNAME"          VARCHAR(50),
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "ZSZJ_INFRAS"."T_COLLECT_TASK" IS '采集任务表';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_TASK"."TASKNAME" IS '任务名称';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_TASK"."TASKDESC" IS '任务描述';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_TASK"."ENABLEDMARK" IS '启用标志 1-启用 0-停用';


-- 2. 采集网站配置表
CREATE TABLE IF NOT EXISTS "ZSZJ_INFRAS"."T_COLLECT_SITE" (
    "ID"                VARCHAR(50)     NOT NULL,
    "TASKID"            VARCHAR(50)     NOT NULL,
    "SITENAME"          VARCHAR(100)    NOT NULL,
    "SITEURLS"          TEXT            NOT NULL,
    "RENDERMODE"        INT             DEFAULT 0,
    "PAGELIMIT"         INT             DEFAULT 50,
    "CSSLIST"           VARCHAR(200),
    "CSSTITLE"          VARCHAR(200),
    "CSSCONTENT"        VARCHAR(200),
    "CSSLINK"           VARCHAR(200),
    "CSSDATE"           VARCHAR(200),
    "REQINTERVAL"       INT             DEFAULT 2,
    "REQHEADERS"        TEXT,
    "CREATORTIME"       TIMESTAMP,
    "CREATORUSER"       VARCHAR(50),
    "CREATORUSERNAME"   VARCHAR(50),
    "LASTMODIFYTIME"    TIMESTAMP,
    "LASTMODIFYUSER"    VARCHAR(50),
    "LASTMODIFYUSERNAME" VARCHAR(50),
    "DELETETIME"        TIMESTAMP,
    "DELETEUSER"        VARCHAR(50),
    "DELETEUSERNAME"    VARCHAR(50),
    "ENABLEDMARK"       VARCHAR(10)     DEFAULT '1',
    "SORTCODE"          INT,
    "ORGANIZE"          VARCHAR(50),
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "ZSZJ_INFRAS"."T_COLLECT_SITE" IS '采集网站配置表';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_SITE"."TASKID" IS '关联任务ID';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_SITE"."SITENAME" IS '网站名称';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_SITE"."SITEURLS" IS '入口URL（多个换行分隔）';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_SITE"."RENDERMODE" IS '渲染模式 0-静态 1-动态JS';

CREATE INDEX "IDX_COLLECT_SITE_TASKID" ON "ZSZJ_INFRAS"."T_COLLECT_SITE" ("TASKID");


-- 3. 采集关键字表（子表）
CREATE TABLE IF NOT EXISTS "ZSZJ_INFRAS"."T_COLLECT_KEYWORD" (
    "ID"                VARCHAR(50)     NOT NULL,
    "SITEID"            VARCHAR(50)     NOT NULL,
    "KEYWORD"           VARCHAR(100)    NOT NULL,
    "MATCHSCOPE"        INT             DEFAULT 0,
    "MATCHLOGIC"        INT             DEFAULT 0,
    "ENABLEDMARK"       VARCHAR(10)     DEFAULT '1',
    "SORTCODE"          INT,
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "ZSZJ_INFRAS"."T_COLLECT_KEYWORD" IS '采集关键字表';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_KEYWORD"."MATCHSCOPE" IS '匹配范围 0-标题 1-全文';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_KEYWORD"."MATCHLOGIC" IS '匹配逻辑 0-OR 1-AND';

CREATE INDEX "IDX_COLLECT_KEYWORD_SITEID" ON "ZSZJ_INFRAS"."T_COLLECT_KEYWORD" ("SITEID");


-- 4. 采集结果表
CREATE TABLE IF NOT EXISTS "ZSZJ_INFRAS"."T_COLLECT_RESULT" (
    "ID"                VARCHAR(50)     NOT NULL,
    "TASKID"            VARCHAR(50),
    "SITEID"            VARCHAR(50),
    "SITENAME"          VARCHAR(100),
    "TITLE"             VARCHAR(500),
    "SUMMARY"           TEXT,
    "SOURCEURL"         TEXT,
    "PUBLISHTIME"       TIMESTAMP,
    "COLLECTTIME"       TIMESTAMP,
    "HITKEYWORDS"       VARCHAR(500),
    "READSTATUS"        INT             DEFAULT 0,
    "URLHASH"           VARCHAR(64)     NOT NULL,
    "CATEGORY"          VARCHAR(200),
    "CATEGORYCODE"      VARCHAR(200),
    "DETAIL"            CLOB,
    "HREF"              VARCHAR(500),
    "PROVINCE"          VARCHAR(50),
    "CITY"              VARCHAR(100),
    "JYBXHREF"          VARCHAR(500),
    "SPIDERSTATUS"      VARCHAR(20),
    "SYNCED"            INT             DEFAULT 0,
    "BIDAMOUNT"         VARCHAR(100),
    "BIDWINNER"         VARCHAR(200),
    "BIDDATE"           VARCHAR(50),
    "TITLEID"           VARCHAR(50),
    "PROJECTNAME"       VARCHAR(500),
    "PROJECTCODE"       VARCHAR(100),
    "SECTIONNAME"       VARCHAR(500),
    "MAXPRICE"          VARCHAR(100),
    "OPENTIME"          VARCHAR(100),
    "OPENPLACE"         VARCHAR(500),
    "TENDERER"          VARCHAR(200),
    "TENDERCONTACT"     VARCHAR(100),
    "TENDERTEL"         VARCHAR(50),
    "BUYERPERSON"       VARCHAR(100),
    "BUYERTEL"          VARCHAR(50),
    "WINNERPERSON"      VARCHAR(100),
    "WINNERTEL"         VARCHAR(50),
    "CREATORTIME"       TIMESTAMP,
    "CREATORUSER"       VARCHAR(50),
    "LASTMODIFYTIME"    TIMESTAMP,
    "LASTMODIFYUSER"    VARCHAR(50),
    "DELETETIME"        TIMESTAMP,
    "DELETEUSER"        VARCHAR(50),
    "ENABLEDMARK"       VARCHAR(10)     DEFAULT '1',
    "SORTCODE"          INT,
    "ORGANIZE"          VARCHAR(50),
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "ZSZJ_INFRAS"."T_COLLECT_RESULT" IS '采集结果表';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."URLHASH" IS 'URL MD5去重';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."READSTATUS" IS '0-未读 1-已读 2-归档';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."SPIDERSTATUS" IS '详情同步状态';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."SYNCED" IS '0-待同步 1-已同步';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."DETAIL" IS '详情正文';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."BIDAMOUNT" IS '中标金额';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."BIDWINNER" IS '中标单位';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."BIDDATE" IS '中标日期';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."PROJECTNAME" IS '招标项目名称';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."SECTIONNAME" IS '标段(包)名称';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."MAXPRICE" IS '最高投标限价（万元）';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."OPENTIME" IS '开标时间';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."OPENPLACE" IS '开标地点';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."TENDERER" IS '招标人';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."TENDERCONTACT" IS '招标人联系人';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_RESULT"."TENDERTEL" IS '联系电话';

CREATE UNIQUE INDEX "IDX_COLLECT_RESULT_URLHASH" ON "ZSZJ_INFRAS"."T_COLLECT_RESULT" ("URLHASH");
CREATE INDEX "IDX_COLLECT_RESULT_SYNCED" ON "ZSZJ_INFRAS"."T_COLLECT_RESULT" ("SYNCED");
CREATE INDEX "IDX_COLLECT_RESULT_COLLECTTIME" ON "ZSZJ_INFRAS"."T_COLLECT_RESULT" ("COLLECTTIME");
CREATE INDEX "IDX_COLLECT_RESULT_CATEGORY" ON "ZSZJ_INFRAS"."T_COLLECT_RESULT" ("CATEGORYCODE");
CREATE INDEX "IDX_COLLECT_RESULT_SITEID" ON "ZSZJ_INFRAS"."T_COLLECT_RESULT" ("SITEID");
CREATE INDEX "IDX_COLLECT_RESULT_READSTATUS" ON "ZSZJ_INFRAS"."T_COLLECT_RESULT" ("READSTATUS");


-- 5. 采集日志表
CREATE TABLE IF NOT EXISTS "ZSZJ_INFRAS"."T_COLLECT_LOG" (
    "ID"                VARCHAR(50)     NOT NULL,
    "TASKID"            VARCHAR(50),
    "SITEID"            VARCHAR(50),
    "SITENAME"          VARCHAR(100),
    "TRIGGERTYPE"       INT             DEFAULT 0,
    "EXECSTATUS"        INT             DEFAULT 0,
    "STARTTIME"         TIMESTAMP,
    "ENDTIME"           TIMESTAMP,
    "TOTALCOUNT"        INT             DEFAULT 0,
    "HITCOUNT"          INT             DEFAULT 0,
    "ERRORMSG"          TEXT,
    "SYNCED"            INT             DEFAULT 0,
    "CREATORTIME"       TIMESTAMP,
    "CATEGORY"          VARCHAR(50),
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "ZSZJ_INFRAS"."T_COLLECT_LOG" IS '采集日志表';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_LOG"."TRIGGERTYPE" IS '0-手动 1-定时';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_LOG"."EXECSTATUS" IS '0-执行中 1-成功 2-失败';

CREATE INDEX "IDX_COLLECT_LOG_SYNCED" ON "ZSZJ_INFRAS"."T_COLLECT_LOG" ("SYNCED");
CREATE INDEX "IDX_COLLECT_LOG_EXECSTATUS" ON "ZSZJ_INFRAS"."T_COLLECT_LOG" ("EXECSTATUS");
CREATE INDEX "IDX_COLLECT_LOG_STARTTIME" ON "ZSZJ_INFRAS"."T_COLLECT_LOG" ("STARTTIME");


-- 6. 负责人配置表
CREATE TABLE IF NOT EXISTS "ZSZJ_INFRAS"."T_COLLECT_MANAGER" (
    "ID"                VARCHAR(50)     NOT NULL,
    "PROVINCE"          VARCHAR(50),
    "LEADER"            VARCHAR(50),
    "LEADERNAME"        VARCHAR(50),
    "CHARGEUSER"        VARCHAR(50),
    "CHARGEUSERNAME"    VARCHAR(50),
    "OPENFLAG"          INT             DEFAULT 0,
    "CREATORTIME"       TIMESTAMP,
    "CREATORUSER"       VARCHAR(50),
    "LASTMODIFYTIME"    TIMESTAMP,
    "LASTMODIFYUSER"    VARCHAR(50),
    "DELETETIME"        TIMESTAMP,
    "DELETEUSER"        VARCHAR(50),
    "ENABLEDMARK"       VARCHAR(10)     DEFAULT '1',
    "SORTCODE"          INT,
    "ORGANIZE"          VARCHAR(50),
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "ZSZJ_INFRAS"."T_COLLECT_MANAGER" IS '采集负责人配置表';
COMMENT ON COLUMN "ZSZJ_INFRAS"."T_COLLECT_MANAGER"."OPENFLAG" IS '是否开启推送 1-开启 0-关闭';


-- 7. 推送记录表
CREATE TABLE IF NOT EXISTS "ZSZJ_INFRAS"."T_COLLECT_PUSH_RECORD" (
    "ID"                VARCHAR(50)     NOT NULL,
    "CONTENT"           TEXT,
    "PUSHUSER"          VARCHAR(50),
    "PUSHUSERNAME"      VARCHAR(100),
    "STATISTICSDATE"    TIMESTAMP,
    "CREATORTIME"       TIMESTAMP,
    "CREATORUSER"       VARCHAR(50),
    "LASTMODIFYTIME"    TIMESTAMP,
    "LASTMODIFYUSER"    VARCHAR(50),
    "DELETETIME"        TIMESTAMP,
    "DELETEUSER"        VARCHAR(50),
    "ENABLEDMARK"       VARCHAR(10)     DEFAULT '1',
    "SORTCODE"          INT,
    "ORGANIZE"          VARCHAR(50),
    "FLOWPHASE"         VARCHAR(50),
    "STEPNAME"          VARCHAR(50),
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "ZSZJ_INFRAS"."T_COLLECT_PUSH_RECORD" IS '采集推送记录表';
